# Dockerfile.dev
FROM ruby:3.3.6

WORKDIR /app
RUN apt-get update -qq && apt-get install -y build-essential libmariadb-dev default-mysql-client

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

ENV RAILS_ENV=development

CMD ["rails", "server", "-b", "0.0.0.0"]
