# Dockerfile.dev
FROM ruby:3.3.6

WORKDIR /app
RUN rm -rf /var/lib/apt/lists/* && \
    apt-get update -o Acquire::CompressionTypes::Order::=gz && \
    apt-get install -y --fix-missing build-essential libmariadb-dev mariadb-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*



COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

ENV RAILS_ENV=development

CMD ["rails", "server", "-b", "0.0.0.0"]
