default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: rails_user
  password: vps-taka-study
  host: localhost

development:
  <<: *default
  database: dev-vps-taka-study-db

test:
  <<: *default
  database: test-vps-taka-study-db

production:
  <<: *default
  database: prod-vps-taka-study-db
