default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  host: localhost

development:
  <<: *default
  database: service1_db
  username: root
  host: localhost

test:
  <<: *default
  database: app_name_test

production:
  <<: *default
  # mysqlの設定のところで入力した情報を以下に記述
  database: service1_db
  username: dbuser
  password: cent_taku_enginner
  socket: /var/lib/mysql/mysql.sock
